### ISSUE TITLE
revert not working

### ISSUE THREAD

**Issue by SLIPotter** [ASHTeam/ash-aio-2#3] opened 2017-02-06 04:55 UTC
**Describe your issue**:
my hacks won't revert 

**Which version of AshAIO are you on (find your version in the title bar of AshAIO)**:

2.0.0.1
**Steps to reproduce issue/bug**:
number one most likely update i now this is like 2 days old but still now i need to use old ash

**Expected result**:

restarts work
**Actual result**:
restarts work
Thank you for filling out this form, ASH Team will get back to you shortly.

**Comment by sanelkukic** [comment] 2017-02-06 14:05
Duplicate of #1, closing

**Closed as completed by sanelkukic** 2017-02-06 14:05 UTC
Labels: duplicate
